# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQDjDdpEJbRQCKqXjR7G5Y_XJy6e1SAb
"""

#an addiction tracker.
#Forgot to add notation as i was doing it so... good luck?

import json
import os
from datetime import datetime

urge_log = "urge_log.json"

def activity_log():
  if not os.path.exists(urge_log):
    return[]
  with open(urge_log, "r") as f:
    return json.load(f)

def log_new_urge(intensity):
  load_logs = activity_log()
  time = datetime.now().strftime("%H:%M %d/%m/%Y")
  new_urge = {
      "datetime": time,
      "intensity": intensity
  }

  load_logs.append(new_urge)
  with open(urge_log, "w") as f:
    json.dump(load_logs, f, indent=4)
    print(f"Logged new urge successfully. [{time}]")

def stats():
  load_logs = activity_log()
  total_urges = len(load_logs)

  last_urge = load_logs[-1]
  return total_urges, f"{last_urge['datetime']}"

def show_logs():
  load_logs = activity_log()
  print(f"URGE LOG:")
  if not load_logs:
    print("No entries found.")
    return

  for index, entry in enumerate(load_logs, start=1):
    print(f"{index}. [{entry['datetime']}] | Intensity: {entry['intensity']}")

def reset():
  with open(urge_log, "w") as f:
    json.dump([], f, indent=4)

print("If you are unsure, enter 'help'")

while True:
  print()
  user_input = input("> ")
  if user_input == "help":
    print()
    print("OPTIONS DASHBOARD:")
    print("1.) LOG URGE")
    print("2.) OPEN URGE LOGS")
    print("3.) RESET")
    print("4.) EXIT")
    print("(SELECT NUMBER OF DESIRED OPTION)")
    print()
  elif user_input == "1":
    colour = input("Intensity? (r/a/g) ")
    if colour == "r":
      log_new_urge("Red")
    elif colour == "a":
      log_new_urge("Amber")
    elif colour == "g":
      log_new_urge("Green")
    else:
      print("INVALID")
  elif user_input == "2":
    show_logs()
  elif user_input == "3":
    confirm = input(f"Are you sure? y/N ")
    if confirm == "y" or confirm == "Y":
      reset()
    else:
      print("Action aborted or input invalid. Nothing has been changed.")
  elif user_input == "4":
    break
  else:
    print("INVALID")